# This is the configuration used to check the rubocop source code.

Documentation:
    Enabled: false

AllCops:
  Exclude:
    - 'vendor/**/*'
    - 'tmp/**/*'
    - 'storage/**/*'
    - 'results/**/*'
    - 'db/**/*'
    - 'bin/**'

  TargetRubyVersion: 2.5.1

Layout/ClassStructure:
  Enabled: true
  Categories:
    module_inclusion:
      - include
      - prepend
      - extend
  ExpectedOrder:
      - module_inclusion
      - constants
      - public_class_methods
      - initializer
      - instance_methods
      - protected_methods
      - private_methods

Metrics/BlockLength:
  Exclude:
    - 'Rakefile'
    - '**/*.rake'
    - 'spec/**/*.rb'
    - '**/*.gemspec'

Metrics/ModuleLength:
  Exclude:
    - 'spec/**/*.rb'
