resources:
- repo: self
queue:
  name: Hosted Ubuntu 1604
steps:
- task: Docker@0
  displayName: 'Build image'
  inputs:
    action: 'Run a Docker command'

    customCommand: 'build -t $(Build.Repository.Name):$(Build.BuildId) --build-arg CI=true --build-arg CODECOV_TOKEN=$(CODECOV_TOKEN)'

  continueOnError: true

- task: Docker@0
  displayName: 'Create temp container'
  inputs:
    action: 'Run a Docker command'

    customCommand: 'create --name hotsauced $(Build.Repository.Name):$(Build.BuildId)'


- task: Docker@0
  displayName: 'Copy test results to workspace'
  inputs:
    action: 'Run a Docker command'

    customCommand: 'cp hotsauced:usr/src/app/results .'


- task: Docker@0
  displayName: 'Run a Docker command'
  inputs:
    action: 'Run a Docker command'

    customCommand: 'rm hotsauced'


- task: PublishTestResults@2
  displayName: 'Publish Test Results results/*.xml'
  inputs:
    testResultsFiles: 'results/*.xml'



